api/urls.py
from django.urls import path, include


urlpatterns = [

    path('v1/', include(('api.v1.urls', 'v1'))),
    path('api-auth/', include('rest_framework.urls')),
]

apps/menu/models.py
from django.core.validators import URLValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from .constants import TargetType, PositionType


class Element(models.Model):
    """Model for menu items"""

    name = models.CharField(_("Name"), max_length=150)

    url = models.CharField(_("URL"),
                           max_length=200,
                           help_text=_('Example: https://google.com/ or /testPage/'),
                           validators=[URLValidator]
                           )
    target = models.CharField(_("Url type"), max_length=2, choices=TargetType.choices, default=TargetType.SELF)
    position = models.CharField(_("Position"), max_length=2, choices=PositionType.choices)
    enabled = models.BooleanField(_("Enabled"), default=True)
    weight = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['weight']
        verbose_name = _("Element")
        verbose_name_plural = _("Elements")

markup/templates/base.jinja
<!DOCTYPE html>
<html class="h-100">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ site_name }}{% endblock %}</title>

    <link href="{{  static("css/bootstrap.min.css") }}" rel="stylesheet">
    <link href="{{  static("css/style.css") }}" rel="stylesheet">

    <script src="{{  static("js/popper.min.js") }}"></script>
    <script src="{{  static("js/bootstrap.min.js") }}"></script>
    <script src="{{ static("js/jquery-3.6.0.min.js") }}"></script>
    <script src="{{ static("js/modal.js") }}"></script>

    <link rel="shortcut icon" type="image/png" href="{{ static('favicon.ico') }}"/>

    {% block head %}{% endblock %}


</head>

<body class="d-flex flex-column h-100">


    <div class="page-container">
        <div class="content-wrap">

            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
              <div class="container-fluid">
                <a class="navbar-brand" href="{{ url("home") }}">{{ site_name }}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% for object in menu %}
                            {% if object.position == "HE" %}
                                <li class="nav-item">
                                  <a class="nav-link" target="{{ object.get_target_display() }}" href="{{ object.url }}">{{ object.name }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}



                  </ul>
                <ul class="navbar-nav mb-2 mb-lg-0">

                    <li class="nav-item dropdown">
                        <form action="{{ url("set_language") }}" method="post">
                            {% csrf_token %}
                            {{ language_form().as_p() }}
                        </form>
                    </li>

                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{{ url("account:profile") }}" tabindex="-1" aria-disabled="true">{{ _("Account") }}</a>
                        <a class="nav-link" href="{{ url("account:logout") }}" tabindex="-1" aria-disabled="true">{{ _("Logout") }}</a>
                    {% else %}
                        <a class="nav-link" href="{{ url("account:login") }}" tabindex="-1" aria-disabled="true">{{ _("Login") }}</a>
                    {% endif %}
                </ul>

                </div>
              </div>
            </nav>


            {% for message in messages %}

                <div class="alert {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}alert-danger{% else %}alert-success{% endif %} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>

            {% endfor %}

            {% if breadcrumbs %}
                {{ breadcrumbs }}
            {% endif %}

            <div class="modal" id="mainModal" tabindex="-1">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title"></h5>
                  </div>
                  <div class="modal-body">
                  </div>
                  <div class="modal-footer">
                  </div>
                </div>
              </div>
            </div>

        </div>
    </div>

    {% block body %}
    {% endblock %}


    <footer class="footer mt-auto py-3 bg-dark">
          <div class="container" style="width: auto; max-width: 680px; padding: 0 15px;">
                <hr>
                <div style="text-align: center;">
                    {% for object in menu %}
                        {% if object.position == "FO" %}
                            <a  target="{{ object.get_target_display() }}" href="{{ object.url }}">{{ object.name }}</a>
                        {% endif %}
                    {% endfor %}
                </div>
          </div>
    </footer>

</body>
</html>

markup/templates/breadcrumbs.jinja
{% if breadcrumbs %}
    <nav class="ms-3 mt-3" aria-label="breadcrumb">
      <ol class="breadcrumb">
          {% for data in breadcrumbs %}
              {% if data == breadcrumbs|last %}
                <li class="breadcrumb-item active" aria-current="page">{{ data[0] }}</li>
              {% else %}
                <li class="breadcrumb-item"><a href="{{ data[1] }}">{{ data[0] }}</a></li>
              {% endif %}
          {% endfor %}

      </ol>
    </nav>
{% endif %}

markup/templates/error.jinja
{% extends "base.jinja" %}

{% block title %}Error {{ error_code }}{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ static('/css/error.css') }}">
{% endblock %}

{% block body %}
    	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>Oops!</h1>
				<h2>{{ error_code }} - {{ error_message }}</h2>
			</div>

			<a href="{{url('home') }}" class="btn btn-primary">{{ _("Return to main") }}</a>
		</div>
	</div>
{% endblock %}