api/urls.py
from django.urls import path, include


urlpatterns = [

    path('v1/', include(('api.v1.urls', 'v1'))),
    path('api-auth/', include('rest_framework.urls')),
]

apps/movie/urls.py
from django.urls import path
from apps.movie.views import *

urlpatterns = [
    path("", AnimeListView.as_view(), name="home"),
    path("<slug:slug>/", AnimeDetailView.as_view(), name="detail"),
    path("<slug:slug>/<int:season>/", AnimeDetailView.as_view(), name="detail"),
]

apps/movie/models.py
import os

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from solo.models import SingletonModel

from apps.movie.constants import AnimeType
from apps.movie.managers import AnimeManager
from shared.services.slugify import unique_slugify

ALLOWED_VIDEO_FORMATS = ['webm', 'mpg', 'ogg', 'mp4', 'mpeg']


class Tag(models.Model):
    """Tag model"""
    name = models.CharField(_("Name"), max_length=150, unique=True)
    display = models.BooleanField(_("Display"), default=True)

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")

    def __str__(self):
        return f"#{self.name}"

    def get_absolute_url(self):
        return f"{reverse('movie:home')}?search=%23{self.name}"


class Style(models.Model):
    """Style model for Anime model customization"""
    name = models.CharField(_("Name"), unique=True, max_length=150)
    style = models.TextField(_("Style"), blank=True)
    background = models.ImageField(_("Background"), blank=True, null=True, upload_to="style/")

    def __str__(self):
        return self.name


class Anime(models.Model):
    """Anime object model"""
    name = models.CharField(_("Name"), max_length=150)
    lang = models.CharField(_("Language"), max_length=10, choices=settings.LANGUAGES, default=settings.LANGUAGE_CODE)
    type = models.CharField(_("Content type"), max_length=2, choices=AnimeType.choices, default=AnimeType.SERIAL)
    slug = models.SlugField(blank=True)
    poster = models.ImageField(_("Poster"), upload_to="posters/%Y/%m/%d/")
    style = models.ForeignKey(Style, null=True, blank=True, related_name="anime", on_delete=models.SET_NULL)
    tags = models.TextField(_("Tags"), blank=True)
    tag_list = models.ManyToManyField(Tag, blank=True, related_name="anime")
    rating = models.PositiveIntegerField(_("Rating"), default=0)

    objects = AnimeManager()

    class Meta:
        verbose_name = _("Anime")
        verbose_name_plural = _("Anime's")
        unique_together = [('slug', 'lang')]
        ordering = ['name']

    def __init__(self, *args, **kwargs):
        super(Anime, self).__init__(*args, **kwargs)
        self._tags = self.tags

    def __str__(self):
        return self.name

    def save(self, **kwargs):
        """Creating unique slug for model if slug not set"""
        if not self.slug:
            unique_slugify(self, f"{self.name}")
        super().save(**kwargs)

    def get_absolute_url(self):
        return reverse("movie:detail", kwargs={"slug": self.slug})


class Season(models.Model):
    """Season model"""
    name = models.CharField(_("Name"), max_length=150)
    description = models.TextField(_("Description"))
    number = models.PositiveSmallIntegerField()
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE, related_name="seasons")

    class Meta:
        verbose_name = _("Season")
        verbose_name_plural = _("Seasons")
        unique_together = [('number', 'anime')]
        ordering = ['number']

    def __str__(self):
        return _("%s | Season #%s") % (self.anime.name, self.number)

    def get_absolute_url(self):
        return reverse("movie:detail", kwargs={"slug": self.anime.slug, "season": self.number})


class Quality(models.Model):
    """Quality model"""
    name = models.CharField(_("Name"), max_length=15, unique=True)
    wight = models.SmallIntegerField(default=0)
    default = models.BooleanField(default=False)

    class Meta:
        verbose_name = _("Quality")
        verbose_name_plural = _("Quality")
        ordering = ['wight']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.default:
            Quality.objects.filter(default=True).update(default=False)
        super().save(*args, **kwargs)


class Episode(models.Model):
    """Episode model"""
    number = models.PositiveSmallIntegerField()
    season = models.ForeignKey(Season, on_delete=models.CASCADE, related_name="episodes")

    class Meta:
        verbose_name = _("Episode")
        verbose_name_plural = _("Episodes")
        unique_together = [('number', 'season')]
        ordering = ['number']

    def __str__(self):
        return _("Episode %s") % self.number

    def get_absolute_url(self):
        return f"{self.season.get_absolute_url()}?e={self.number}"


def anime_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/movie/files/anime_name/season_name/<filename>
    return 'movie/files/{0}/{1}/{2}/'.format(
        instance.episode.season.anime.name,
        instance.episode.season.name,
        filename)


def extension_validation(object):
    data = object.split('.')
    if len(data) == 1 or data[1] not in ALLOWED_VIDEO_FORMATS:
        raise ValidationError("Not supported extension")


class EpisodeFile(models.Model):
    """Episode File model, unique constraint quality and episode"""
    file = models.FileField(upload_to=anime_path, blank=True, validators=[FileExtensionValidator(ALLOWED_VIDEO_FORMATS)])
    path = models.CharField("File path", max_length=150, blank=True, validators=[extension_validation])
    quality = models.ForeignKey(Quality, on_delete=models.CASCADE)
    episode = models.ForeignKey(Episode, on_delete=models.CASCADE, related_name="files")

    class Meta:
        verbose_name = _("Episode File")
        verbose_name_plural = _("Episode Files")
        unique_together = [('quality', 'episode')]

    def __str__(self):
        return f"{self.episode}/{self.quality}"


class Review(models.Model):
    """Review model"""
    season: Season = models.ForeignKey(Season, on_delete=models.CASCADE, related_name="reviews")
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    text = models.TextField(_("Review"))

    datetime = models.DateTimeField(auto_now_add=True)
    verified = models.BooleanField(default=False)

    class Meta:
        verbose_name = _("Review")
        verbose_name_plural = _("Reviews")

    def __str__(self):
        return _("Review #%s") % self.pk


class Subscribe(models.Model):
    """User subscribe to anime model"""
    anime: Anime = models.ForeignKey(Anime, on_delete=models.CASCADE, related_name="subscribes")
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="subscribes")

    class Meta:
        unique_together = [('anime', 'user')]


def anime_image_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/movie/season_images/anime_name/season_name/<filename>
    return 'movie/season_images/{0}/{1}/{2}/'.format(
        instance.season.anime.name,
        instance.season.name,
        filename)


class AnimeImage(models.Model):
    season: Season = models.ForeignKey(Season, on_delete=models.CASCADE, related_name="images")
    file = models.ImageField(upload_to=anime_image_path)
    wight = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name = _("Anime Image")
        verbose_name_plural = _("Anime Images")
        ordering = ['wight']

    def __str__(self):
        return _("AnimeImage #%s") % self.pk


class Rating(models.Model):
    """Anime rating model"""
    val = models.PositiveSmallIntegerField(default=0)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="ratings")
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE, related_name="ratings")

    class Meta:
        verbose_name = _("Rating")
        verbose_name_plural = _("Ratings")
        unique_together = [('user', 'anime')]


class MovieSettings(SingletonModel):
    """Model of Movie settings"""
    movie_per_page = models.PositiveSmallIntegerField(_("Movie per page"),
                                                      help_text=_("How many movies will be shown per page"),
                                                      validators=[MinValueValidator(1)],
                                                      default=10)

    paginator_pages_show = models.PositiveSmallIntegerField(_("Paginator pages show"),
                                                            help_text=_(
                                                                "How many additional pages will be shown in paginator"),
                                                            validators=[MinValueValidator(1)],
                                                            default=3)

    max_reviews_per_season = models.PositiveSmallIntegerField(_("Reviews per season"),
                                                              help_text=_(
                                                                  "How many reviews can a user send on an season"),
                                                              validators=[MinValueValidator(1)],
                                                              default=2)

    min_review_length = models.PositiveSmallIntegerField(_("Min Review length"),
                                                         help_text=_("Minimum length of review text"),
                                                         validators=[MinValueValidator(1)],
                                                         default=20)

    max_review_length = models.PositiveSmallIntegerField(_("Maximum Review length"),
                                                         help_text=_("Maximum length of review text"),
                                                         validators=[MinValueValidator(1)],
                                                         default=500)

    min_rating_val = models.PositiveSmallIntegerField(_("Minimum rating value"),
                                                      validators=[MinValueValidator(1)],
                                                      default=1)

api/v1/movie/views.py
from django.db.models import Count, Q
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _, get_language
from rest_framework import permissions, mixins, status
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from api.mixins import ListRetrieveViewSet, RetrieveViewSet
from api.v1.movie.serializers import *
from apps.movie.filters import AnimeFilter
from apps.movie.models import Episode, Anime, Season, Subscribe


# movide/anime/
# movie/anime/<anime_slug>/
# movie/season/<season_pk>/
# movie/episode/<episode_pk>/
# movie/random/<ignore_anime_slug>/

# movie/subscribe/
# movie/subscribe/<anime_pk>/

# movie/rating/<anime_pk>/
# movie/rating/

# movie/review/


class AnimeViewSet(ListRetrieveViewSet):
    """
    ViewSet for all Anime objects
    """
    serializer_class = AnimeSerializer
    lookup_field = "slug"
    filterset_class = AnimeFilter

    def get_queryset(self):
        return Anime.objects.get_lang_queryset()


class AnimeRandomViewSet(ListRetrieveViewSet):
    """
    ViewSet return random Anime /random/<ignore_slug=None>
    If ignore_slug given anime with that slug will be ignored
    """
    serializer_class = AnimeSerializer
    lookup_field = "slug"

    def get_queryset(self):
        return Anime.objects.get_lang_queryset()

    def get_object(self):
        random_object = self.get_queryset().annotate(seasons_cnt=Count("seasons")) \
            .filter(seasons_cnt__gt=0)
        # If ignore param given
        if 'slug' in self.kwargs:
            random_object = random_object.filter(~Q(slug=self.kwargs['slug']))

        if not random_object:
            raise Http404(_("Recommended Anime not found"))
        return random_object.order_by("?").first()

    def list(self, request, *args, **kwargs):
        """ If no argument not given return object without filter"""
        # Yeah i know that is shit but it's working
        return super(AnimeRandomViewSet, self).retrieve(request, *args, **kwargs)


class SeasonRetrieveViewSet(RetrieveViewSet):
    """Retrieve viewset for Season model"""
    queryset = Season.objects.all()
    serializer_class = SeasonEpisodeSerializer


class EpisodeRetrieveViewSet(RetrieveViewSet):
    """Retrieve viewset for Episode model"""
    queryset = Episode.objects.prefetch_related('files__quality').all()
    serializer_class = EpisodeFileSerializer


class ReviewCreateViewSet(mixins.CreateModelMixin, GenericViewSet):
    """CreateViewSet for Review model"""
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = ReviewSerializer

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class SubscribeCreateDeleteViewSet(GenericViewSet):
    """Create/Delete viewset for Subscribe"""
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = SubscribeSerializer

    def retrieve(self, request, *args, **kwargs):
        """Returns if the player is subscribed to the anime"""
        instance = get_object_or_404(Subscribe, user=self.request.user, anime_id=self.kwargs['pk'])
        return Response({'subscribe': instance is not None})

    def create(self, request, *args, **kwargs):
        """Changed subscribe status and returned it"""
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=False)

        obj, created = Subscribe.objects.get_or_create(
            anime=serializer.validated_data['anime'],
            user=request.user,
            defaults={'anime': serializer.validated_data['anime'], 'user': request.user}
        )

        if not created:
            obj.delete()
        return Response({'subscribe': created}, status=status.HTTP_200_OK)


class RatingCreateUpdateViewSet(GenericViewSet):
    """Create/Update viewset for Rating"""
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = RatingSerializer

    def retrieve(self, request, *args, **kwargs):
        """Returns if the player is subscribed to the anime"""
        instance = get_object_or_404(Rating, user=self.request.user, anime_id=self.kwargs['pk'])
        return Response({'rating': instance.val})

    def create(self, request, *args, **kwargs):
        """Updated subscribe status and returned it"""
        serializer: RatingSerializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        obj, created = Rating.objects.update_or_create(
            anime=serializer.validated_data['anime'],
            user=request.user,
            defaults={'val': serializer.validated_data['val']}
        )

        return Response({"status": "Okay"}, status=status.HTTP_200_OK)

markup/templates/movie/detail.jinja
{% extends 'base.jinja' %}

{% block title %}{{ object.name }}{% endblock title %}

{% block head %}
    <link href="{{ static("movie/css/quality-selector.css") }}" rel="stylesheet">
    <link href="{{ static("movie/css/video-js.css") }}" rel="stylesheet" />
    <link href="{{ static("movie/css/detail.css") }}" rel="stylesheet">

    <script src="{{ static("movie/js/operations.js") }}"></script>

    <script src="{{ static("movie/js/video.min.js") }}"></script>
    <script src="{{ static("movie/js/silvermine-videojs-quality-selector.min.js") }}"></script>

    <script src="{{ static("movie/js/recommended-movie.js") }}"></script>
    <script src="{{ static("movie/js/change-episode.js") }}"></script>

     {% if request.user.is_authenticated %}
        {% if object.type != "FI" %}
            <script src="{{ static("movie/js/subscribe.js") }}"></script>
        {% endif %}
        <script src="{{ static("movie/js/review.js") }}"></script>
        <script src="{{ static("movie/js/rater.min.js") }}" charset="utf-8"></script>
    {% endif %}

    {% if object.style %}
        <style>
            {% if object.style.background %}
            body { background-image: url({{ object.style.background.url }}); }
            {% endif %}
            {{ object.style.style }}
        </style>
    {% endif %}

{% endblock head %}

{% block body %}
    <script>
        {% if request.user.is_authenticated %}
            var username = "{{ request.user.username }}";
            var user_logo = "{{ request.user.get_avatar() }}";
        {% endif %}

        var anime_slug = "{{ object.slug }}";
        var anime_pk = {{ object.pk }};
        var season_pk = {{ season.pk }};
    </script>

    {% set images = season.images.all() %}

    <div class="container">
        <div class="row">
            <h4 class="text-center">{{ object }}: {{ season.name }}</h4>

        <div class="col-4">
            <img src="{{ object.poster.url }}" class="img-thumbnail rounded" alt="">
            <hr>
            <p class="text-center">Anime rating: {{ object.rating }}</p>

            {% if images %}
                <center class="mb-2">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">{{ _("Screenshots") }}</button>
                </center>
            {% endif %}

        </div>

        <div class="col">
            <hr>
            {{ season.description }}
            <hr>

            {% set tags = object.tag_list.filter(display=True) %}

            {% if tags %}
                <div class="tags-links">
                    <span class="fw-bold me-2">{{ _("Tags") }}:</span>
                    {% for tag in tags %}
                        <a href="{{ url("movie:home") }}?search=%23{{ tag.name }}" >{{ tag }}</a>
                    {% endfor %}
                </div>
            {% endif %}

            {% if request.user.is_authenticated and object.type != "FI" %}
                <div id="subscribe" class="mt-3">
                    <button id="unsub" {% if not subscribe %}style="display: none" {% endif %} class="btn btn-secondary">{{ _("Unsubscribe") }}</button>
                    <button id="sub" {% if subscribe %}style="display: none" {% endif %} class="btn btn-success">{{ _("Subscribe") }}</button>
                </div>
            {% endif %}
        </div>

        </div>

        <div class="row">
        {% if rating %}
            <div id="rate"></div>
            <script>
                    $("#rate").rate({
                        max_value: {{ settings.max_rating_val }},
                        step_size: {{ settings.min_rating_val }},
                        initial_value: {{ rating }},
                    }).on("change", function(ev, data){
                        if(data.from != data.to) {
                           request("/api/v1/movie/rating/", "POST", "anime="+ {{ object.pk }} + "&val=" + data.to)
                        }

                    });
            </script>
        {% endif %}
        </div>
        <hr>
        <div class="row">
            <div class="col">
                <select id="seasons" class="form-select form-select-lg mb-3" aria-label=".form-select-lg" {% if season_list|length == 1 %}style="display: none" {% endif %}>
                    {% for num in season_list %}
                        {% if season.number == num %}
                            <option value="{{ num }}" selected>{{ _("Season") }} {{ num }}</option>
                        {% else %}
                            <option href="{{ url("movie:detail", slug=object.slug, season=num) }}" value="{{ num }}">{{ _("Season") }} {{ num }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>

            <div class="col">
                {% if episode_list|length > 0 %}
                    <select id="episodes" class="form-select form-select-lg mb-3" aria-label=".form-select-lg" {% if episode_list|length == 1 %}style="display: none" {% endif %}>
                      {% for episode in episode_list %}
                        <option pk="{{ episode.pk }}" value="{{ episode.number }}">{{ _("Episode") }} {{ episode.number }}</option>
                      {% endfor %}
                    </select>
                {% endif %}
            </div>


            <div class="mh-10">
                <video id="my-video" class="video-js vjs-tech vjs-big-play-centered" controls preload="none" tabindex="-1" data-setup='{"fluid": true}'></video>
            </div>

            <script>
              var options = {
                   controlBar: {
                      children: [
                         'playToggle',
                         'CurrentTimeDisplay',
                         'TimeDivider',
                         'DurationDisplay',
                         'progressControl',
                         'volumePanel',
                         'qualitySelector',
                         'pictureInPictureToggle',
                         'fullscreenToggle',
                      ],
                   },
                };
              var player = videojs('my-video', options, function () {});

            </script>
            <hr>

            <center>
                {% if form %}
                    <h4 class="text-center">{{ _("Reviews") }}</h4>
                    <div id="review">
                        {{ form.media }}
                        {{ form.as_p() }}
                        <button class="btn btn-primary btn-sm">{{ _("Send") }}</button>
                    </div>
                {% endif %}

            <div class="mb-4"></div>
            <hr>
                <div id="review-list" class="col-md-8 col-lg-6">
                    {% if reviews %}
                        {% for review in reviews %}
                            <div class="card mb-4">
                              <div class="card-body">
                                {{ review.text|safe }}
                                <div class="d-flex justify-content-between">
                                  <div class="d-flex flex-row align-items-center">
                                    <img src="{{ review.user.get_avatar() }}" alt="avatar" width="25" height="25" />
                                    <p class="small mb-0 ms-2">{{ review.user.username }}</p>
                                  </div>
                                    <time class="small mb-0 ms-2 text-center">{{ review.datetime|date("d.m.Y, G:i") }}</time>
                                </div>
                              </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>

            </center>

        </div>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">{{ _("Screenshots") }}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">

            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner">
                  {% for image in images %}
                    <div class="carousel-item {% if image == images|first %}active{% endif %}">
                      <img src="{{ image.file.url }}" class="d-block w-100">
                    </div>
                  {% endfor %}
              </div>
            
             {% if images.count() > 1 %}
            
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">{{ _("Previous") }}</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">{{ _("Next") }}</span>
              </button>
            {% endif %}
            </div>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ _("Close") }}</button>
          </div>
        </div>
      </div>
    </div>


{% endblock body %}

markup/templates/movie/list.jinja
{% extends 'base.jinja' %}

{% block head %}

{% endblock %}

{% block body %}

    <!-- Content -->
    <div class="container mx-auto">

        <!-- Search field -->
        <form method="get">
            <div class="input-group mb-3">
              {{ filter.form }}
              <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button">{{ _("Search") }}</button>
              </div>
            </div>
        </form>
        <!-- End Search -->

        <div class="row">
            {% if page_obj %}
            {% for object in page_obj %}
                <div class="col-md-auto">
                    <div class="card mb-3" style="width: 20rem;">
                    <img src="{{ object.poster.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ object.name }}</h5>
                            <p class="card-text">Rating: {{ object.rating }}</p>
                            <a href="{{ object.get_absolute_url() }}" class="btn btn-primary"><i class="fas fa-link"></i> {{ _("View") }}</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% else %}
                <hr>
                <center>
                    <h5>{{ _("Animes not found") }}</h5>
                </center>
            {% endif %}
        </div>
    </div>
    <!-- End content -->

    <!-- Paginator -->
    {% if page_obj.paginator.num_pages > 1 %}
    <nav>
      <ul class="pagination justify-content-center">
          {% if page_obj.has_previous() %}
              <li class="page-item">
               <a class="page-link" href="{{ path }}page={{ page_obj.previous_page_number() }}">{{ _("Previous") }}</a>
              </li>
          {% else %}
              <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1" aria-disabled="true">{{ _("Previous") }}</a>
              </li>
          {% endif %}

          {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number|add(-1 - settings.paginator_pages_show) < i < page_obj.number|add(1 + settings.paginator_pages_show) %}
                    {% if i == page_obj.number %}
                        <li class="page-item page-link active">{{ i }}</li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="{{ path }}page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endif %}
          {% endfor %}

          {% if page_obj.has_next() %}
              <li class="page-item">
               <a class="page-link" href="{{ path }}page={{ page_obj.next_page_number() }}">{{ _("Next") }}</a>
              </li>
          {% else %}
              <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1" aria-disabled="true">{{ _("Next") }}</a>
              </li>
          {% endif %}
      </ul>
    </nav>
{% endif %}

{% endblock body %}